// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate uses the direct (non-pooled) connection; the app itself connects
    // via a driver adapter using DATABASE_URL (see src/prisma/prisma.service.ts).
    url: process.env["DIRECT_URL"],
  },
});
