export const RECONCILIATION_REPOSITORY = Symbol('RECONCILIATION_REPOSITORY');
export const MATCHING_STRATEGY = Symbol('MATCHING_STRATEGY');

export const MIN_MATCH_SCORE = 20;
export const MAX_DATE_DIFFERENCE_DAYS = 5;
export const DATE_SCORE_WEIGHT = 60;
export const DESCRIPTION_SCORE_WEIGHT = 40;
export const AMOUNT_MATCH_EPSILON = 0.01;
