export const FINANCIAL_SCORE_CALCULATOR = Symbol('FINANCIAL_SCORE_CALCULATOR');

export const SAVINGS_RATE_WEIGHT = 0.4;
export const BUDGET_COMPLIANCE_WEIGHT = 0.35;
export const EXPENSE_GROWTH_WEIGHT = 0.25;

export const CASH_FLOW_TREND_TOLERANCE_PERCENT = 5;

export const SCORE_THRESHOLD_EXCELLENT = 90;
export const SCORE_THRESHOLD_GOOD = 75;
export const SCORE_THRESHOLD_NEEDS_ATTENTION = 50;
