export const BUDGET_REPOSITORY = Symbol('BUDGET_REPOSITORY');

export const MAX_NAME_LENGTH = 100;

export const BUDGET_WARNING_THRESHOLD_PERCENTAGE = 80;
export const BUDGET_EXCEEDED_THRESHOLD_PERCENTAGE = 100;
